apiVersion: v1
kind: ConfigMap
metadata:
  name: forestroots-config
  namespace: forestroots
data:
  NODE_ENV: production
  CLIENT_URL: https://forestroots.example.com
  USER_SERVICE_URL: http://user-service:4101
  PRODUCT_SERVICE_URL: http://product-service:4102
  ORDER_SERVICE_URL: http://order-service:4103
  NOTIFICATION_SERVICE_URL: http://notification-service:4104
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: forestroots
  POSTGRES_DB_USERS: forestroots_users
  POSTGRES_DB_PRODUCTS: forestroots_products
  POSTGRES_DB_ORDERS: forestroots_orders
  POSTGRES_DB_NOTIFICATIONS: forestroots_notifications

